### ISSUE TITLE
Uncaught Error: toString failed

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/jmp#22]
See https://github.com/nteract/hydrogen/issues/491 and https://github.com/nodejs/node/pull/4394

---

I'm getting this error when trying to `print` a (rather large) variable. After the error, trying to run other lines gives a checkmark but no actual output.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package, v0.15.0

### Stack Trace

Uncaught Error: toString failed

```
At events.js:154

Error: toString failed
    at Buffer.toString (buffer.js:490:11)
    at toJSON (/Users/dnowacki/.atom/packages/Hydrogen/node_modules/jmp/index.js:225:33)
    at Function.Message._decode (/Users/dnowacki/.atom/packages/Hydrogen/node_modules/jmp/index.js:217:18)
    at Socket.<anonymous> (/Users/dnowacki/.atom/packages/Hydrogen/node_modules/jmp/index.js:330:35)
    at emitMany (events.js:121:13)
    at Socket.emit (events.js:195:7)
    at Socket._flushRead (/Users/dnowacki/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:638:15)
    at Socket._flushReads (/Users/dnowacki/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:676:23)
    at _zmq.onReadReady (/Users/dnowacki/.atom/packages/Hydrogen/node_modules/zmq/lib/index.js:297:10)
```

**Comment by n-riesco** [comment]
[Message::_decode](https://github.com/n-riesco/jmp/blob/54b0414cf7c89cab5c4da48584f7d38b745fcb20/index.js#L167) can throw this error.

[Message::on](https://github.com/n-riesco/jmp/blob/54b0414cf7c89cab5c4da48584f7d38b745fcb20/index.js#L318) wraps message listeners with a callback that invokes calls `Message::_decode`.

[Message::once](https://github.com/n-riesco/jmp/blob/54b0414cf7c89cab5c4da48584f7d38b745fcb20/index.js#L358) wraps message listeners with a callback that invokes calls `Message::_decode`.

[Message::_encode](https://github.com/n-riesco/jmp/blob/54b0414cf7c89cab5c4da48584f7d38b745fcb20/index.js#L235) creates buffers.

[Message::send](https://github.com/n-riesco/jmp/blob/54b0414cf7c89cab5c4da48584f7d38b745fcb20/index.js#L297) calls `Message::_encode`.

**Comment by n-riesco** [comment]
At the moment, I'm inclined to work around this issue by wrapping the body of [Message::_decode](https://github.com/n-riesco/jmp/blob/54b0414cf7c89cab5c4da48584f7d38b745fcb20/index.js#L167) in a `try-catch` block and return `null` if an exception of this kind is thrown.
